dist: trusty
sudo: false
language: go
go:
- 1.9.1

before_install:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    cd ../.. &&
    mv coveo terraform-providers &&
    cd terraform-providers/terraform-provider-aws;
  fi

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- if [ ${TRAVIS_TAG::1} = v ];
  then
    bash scripts/gogetcookie.sh &&
    go get github.com/kardianos/govendor;
  fi

script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    make test &&
    make vendor-status &&
    make vet;
  fi

# branches:
#   only:
#   - master
  
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

after_success:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    curl -sL https://git.io/goreleaser | bash;
  fi
