dist: trusty
sudo: required
services:
  - docker
language: go
go:
- "1.11"
go_import_path: github.com/terraform-providers/terraform-provider-aws

git:
  depth: 1

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- if [ ${TRAVIS_TAG::1} = v ];
  then
    bash scripts/gogetcookie.sh &&
    go get github.com/kardianos/govendor;
  fi

script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    make test &&
    make vendor-status;
  fi

# branches:
#   only:
#   - master
  
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

after_success:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    curl -sL https://git.io/goreleaser | bash;
  fi
